[package]
name = "zyxt"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
regex = "1.5.4"
enum-as-inner = "0.3.3"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3